repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: detect-private-key
    - id: requirements-txt-fixer
      args:
        - requirements.txt


-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      exclude: ^docs/|^scripts

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
    - id: reorder-python-imports
      language_version: python3

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
    - id: pyupgrade

-   repo: https://github.com/psf/black
    rev: 22.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
    - id: black
      language_version: python3

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    - id: mypy
      language_version: python3
